### ISSUE TITLE
Abstract method causing fatal error in PHP8

### ISSUE THREAD

**Issue by emteknetnz** [sminnee/phpunit-mock-objects#7]
Failure on the PHP8 build for [silverstripe/mfa](https://travis-ci.com/github/silverstripe/silverstripe-mfa/jobs/45125778) that looks like it may be related to sminnee/phpunit-mock-objects

PHP Fatal error:  Class Mock_StoreInterface_562bf448 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SilverStripe\MFA\Store\StoreInterface::__construct) in /home/travis/build/silverstripe/silverstripe-mfa/vendor/sminnee/phpunit-mock-objects/src/Framework/MockObject/Generator.php(345) : eval()'d code on line 1
Fatal error: Class Mock_StoreInterface_562bf448 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SilverStripe\MFA\Store\StoreInterface::__construct) in /home/travis/build/silverstripe/silverstripe-mfa/vendor/sminnee/phpunit-mock-objects/src/Framework/MockObject/Generator.php(345) : eval()'d code on line 1

**Comment by sminnee** [comment]
Hrm, __construct defined by an interface is pretty weird. Perhaps the mock-system no longer supports that in PHP8. Presumably the mocked object in PHP7 isn't actually complying with this interface (as you're not really using a constructor, and not passing it the required Member property.

I expect the error is being introduced not because the mocker has a bug but because PHP8 is a bit stricter about pointing out the error here.

My recommendation would be to remove the __construct method from the interface definition; it feels like an anti-pattern.

**Comment by emteknetnz** [comment]
Closing issue as it appears to be an issue on mfa, rather than this module.

Cheers for your help with this Sam.
